# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
- repo: self
  clean: true

pool:
  name: Hosted VS2017
  demands: npm

variables:
  BuildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'NPM Install'
  inputs:
    workingDir: ChamadoFacil/ChamadoFacil/ChamadoFacil.UserInterface
    verbose: true

- task: Npm@1
  displayName: 'NPM Install Angular CLI'
  inputs:
    command: custom
    workingDir: ChamadoFacil/ChamadoFacil/ChamadoFacil.UserInterface
    verbose: false
    customCommand: 'install -g @angular/cli'

- task: Npm@1
  displayName: 'NPM Run Production'
  inputs:
    command: custom
    workingDir: ChamadoFacil/ChamadoFacil/ChamadoFacil.UserInterface
    verbose: false
    customCommand: 'ng build --prod --aot'